src/nalkinscloud_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('nalkinscloud_ui.urls')),

    # api urls
    path('api/', include('nalkinscloud_api.urls')),

    # OAUTH URLS
    path('', include('oauth2_provider.urls', namespace='oauth2_provider')),
    # Django auth urls
    path('', include('django.contrib.auth.urls')),

    # all auth
    path('accounts/', include('allauth.urls')),

    path('nalkinsadmin/', admin.site.urls),
]

src/nalkinscloud_ui/urls.py
from django.urls import path, re_path
from django.contrib.auth.decorators import login_required

from nalkinscloud_ui import views

app_name = 'nalkinscloud_ui'

urlpatterns = [
    re_path(r'^$', views.index, name='index'),

    # General
    path('login/', views.login_page, name='login'),
    path('login_process/', views.login_process, name='login_process'),
    path('logout_process/', views.logout_process, name='logout_process'),

    # Email verifications urls
    path('verify_account/<uuid:verification_uuid>/', views.VerifyEmailUUIDView.as_view(), name='verify_account'),

    path('devices/', login_required(views.DevicesListView.as_view()), name='devices'),
]

src/nalkinscloud_mosquitto/models.py
from datetime import timedelta, datetime, timezone

from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.core.validators import MaxValueValidator, MinValueValidator
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser

from django_user_email_extension.models import User


class DeviceTypeManager(models.Manager):
    def create_device_type(self, type_name):
        if not type_name:
            raise ValueError('Device type is mandatory')
        return self.create(type=type_name)


class DeviceType(models.Model):
    type = models.CharField(_('Device Type Name'), max_length=32, null=False, primary_key=True)
    date_created = models.DateTimeField(_('Date Created'),  auto_now_add=True, blank=True)

    def __str__(self):
        return self.type

    class Meta:
        verbose_name = _('device_type')
        verbose_name_plural = _('device_type')
        db_table = 'device_type'

    objects = DeviceTypeManager()


class DeviceModelManager(models.Manager):
    def create_device_model(self, model_name):
        if not model_name:
            raise ValueError('Device Model is mandatory')
        return self.create(model=model_name)


class DeviceModel(models.Model):
    model = models.CharField(_('Device Model Name'), max_length=32, null=False, primary_key=True)
    date_created = models.DateTimeField(_('Date Created'),  auto_now_add=True, blank=True)

    def __str__(self):
        return self.model

    class Meta:
        verbose_name = _('device_model')
        verbose_name_plural = _('device_model')
        db_table = 'device_model'

    objects = DeviceModelManager()


class DeviceManager(BaseUserManager):
    def create_device(self, device_id, password, **extra_fields):
        """
        Creates and saves a Device with the given device_id and password.
        """
        if not device_id:
            raise ValueError('Device id must be set')
        if not password:
            raise ValueError('Password must be set')
        device = self.model(device_id=device_id, **extra_fields)
        device.set_password(password)
        device.save()
        return device


class Device(AbstractBaseUser):
    device_id = models.CharField(_('Device Id'), max_length=32, null=False, primary_key=True)
    password = models.CharField(_('Password'), max_length=128, null=False)
    _password = None
    super = models.BooleanField(_('Super User'), default=False,)
    is_enabled = models.BooleanField(_('Device Enabled'), default=False,)
    model = models.ForeignKey(DeviceModel, on_delete=models.CASCADE, null=False)
    type = models.ForeignKey(DeviceType, on_delete=models.CASCADE, null=False)
    date_created = models.DateTimeField(_('Date Created'), auto_now_add=True, blank=True)
    last_update_date = models.DateTimeField(auto_now=True)
    last_login = models.DateTimeField(blank=True, null=True)
    last_login_ip = models.GenericIPAddressField('Connected From', null=True, blank=True)

    objects = DeviceManager()

    USERNAME_FIELD = 'device_id'
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.device_id

    class Meta:
        verbose_name = _('device')
        verbose_name_plural = _('devices')
        db_table = 'devices'


class CustomerDevice(models.Model):
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    device_id = models.ForeignKey(Device, on_delete=models.CASCADE)
    is_owner = models.BooleanField(
        _('Ownership Status'),
        default=False,
        help_text=_('Define if current user is the owner of current device.'),
    )
    __original_is_owner = None
    is_owner_status_updated_at = models.DateTimeField(null=True, editable=False)
    device_name = models.CharField(_('Device Name'), max_length=32, null=False)
    date_created = models.DateTimeField(_('Date Created'),  auto_now_add=True, blank=True)

    def __str__(self):
        return self.user_id.email + ' <-> ' + self.device_id.device_id

    class Meta:
        unique_together = ('user_id', 'device_id',)  # Set primary combined key
        verbose_name = _('customer_device')
        verbose_name_plural = _('customer_device')
        db_table = 'customer_device'

    def save(self, *args, **kwargs):
        # check if there is a change is the is_owner field
        if self.is_owner != self.__original_is_owner:
            # update timestamp
            self.is_owner_status_updated_at = datetime.now(tz=timezone.utc)

        # allow exactly single 'is_owner=True' value per 'device/user'
        if self.is_owner:
            # get all customer devices of current saved device_id that have the is_owner True value, and set it to False
            CustomerDevice.objects.filter(device_id=self.device_id, is_owner=True).update(is_owner=False)

        # save new is_owner state to __original_is_owner for future checks
        self.__original_is_owner = self.is_owner
        super(CustomerDevice, self).save(*args, **kwargs)

    def get_user_id(self):
        return self.user_id


class AccessList(models.Model):
    device = models.ForeignKey(Device, on_delete=models.CASCADE)
    topic = models.CharField(_('Message Topic'), max_length=256, null=False)
    rw = models.IntegerField(_('Read Write Mode'),
                             validators=[MaxValueValidator(2), MinValueValidator(0)],
                             null=False,
                             default=1)
    is_enabled = models.BooleanField(_('ACL Enabled'), default=False)
    date_created = models.DateTimeField(_('Date Created'),  auto_now_add=True, blank=True)
    last_update_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return 'device: ' + self.device.device_id + ' can access ' + self.topic

    class Meta:
        unique_together = (('device', 'topic'),)
        verbose_name = _('access_list')
        verbose_name_plural = _('access_list')
        db_table = 'access_list'


class Message(models.Model):
    message_id = models.AutoField(primary_key=True)
    device = models.ForeignKey(Device, on_delete=models.CASCADE)
    topic = models.CharField(_('Message Topic'), max_length=256, null=False)
    message = models.CharField(_('Message Body'), max_length=256, null=False)
    qos = models.IntegerField(_('QOS'), validators=[MaxValueValidator(1), MinValueValidator(0)], null=False, default=1)
    date_created = models.DateTimeField(_('Date Created'),  auto_now_add=True, blank=True)

    def __str__(self):
        return 'Message of device: ' + self.device.device_id

    class Meta:
        verbose_name = _('messages')
        verbose_name_plural = _('messages')
        db_table = 'messages'

src/templates/base.html
{% load static %}
{% load socialaccount %}
{% if user.is_authenticated %}
    {% get_social_accounts user as social_accounts %}
{% endif %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description"
          content="Automation IOT project">
    <meta name="author" content="{{ developer }}">

    <title>{{ project_name }} Project</title>

    <meta property="og:title" content="{{ project_name }} Project"/>
    <meta property="og:description" content="IOT Automation"/>
    <meta property="og:url" content="https://nalkins.cloud/"/>
    <meta property="og:image" content=""/>
    <link rel="shortcut icon" href="" type="image/x-icon"/>

    <!-- Bootstrap 4 core CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <!-- GitHub Bootstrap Social Buttons -->
    <link href="{% static 'bootstrap-social-gh-pages/bootstrap-social.css' %}" rel="stylesheet">
    <link href="{% static 'bootstrap-social-gh-pages/assets/css/font-awesome.css' %}" rel="stylesheet">
</head>


<body id="page-top">
<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
    <div class="container" role="navigation">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand js-scroll-trigger" href="/#page-top">{{ project_name }}</a>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link js-scroll-trigger" href="{% url 'nalkinscloud_ui:devices' %}">Devices</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link js-scroll-trigger" href="{% url 'nalkinscloud_ui:logout_process' %}">Logout</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link js-scroll-trigger" href="{% url 'nalkinscloud_ui:login' %}">Login</a>
                    </li>
                {% endif %}
            </ul>

        </div>

    </div>

</nav>
{% block body_block %} {% endblock %}
</body>
<footer class="footer bg-light fixed-bottom">
    <div class="container">
        <div class="row">
            <div class="col-lg-6 h-100 text-center text-lg-left my-auto">
                <ul class="list-inline mb-0">
                    <li class="list-inline-item">
                        <p class="text-muted small mb-4 mb-lg-0">Copyright &copy; {{ developer }} {{ current_year }}.
                            All Rights Reserved.</p>
                    </li>
                </ul>
                <ul class="list-inline mb-0">
                    <li class="list-inline-item">
                        <p class="text-muted small mb-4 mb-lg-0">Version: {{ version }}</p>
                    </li>
                    <li class="list-inline-item">|</li>
                    <li class="list-inline-item">
                        <p class="text-muted small mb-4 mb-lg-0">Hostname: {{ hostname }}</p>
                    </li>
                    <li class="list-inline-item">|</li>
                    <li class="list-inline-item">
                        <p class="text-muted small mb-4 mb-lg-0">Environment: {{ environment }}</p>
                    </li>
                </ul>
            </div>
            {% if user.is_authenticated %}
                <div class="col-lg-6 h-100 text-center text-lg-right my-auto">

                    <!-- Print current users email -->
                    <ul class="list-inline mb-0">
                        <li class="list-inline-item">
                            <p class="text-muted small mb-4 mb-lg-0">Logged in user: {{ user.email }}</p>
                        </li>
                    </ul>

                    <!-- Print current users providers -->
                    <ul class="list-inline mb-0">
                        <li class="list-inline-item">
                            <p class="text-muted small mb-4 mb-lg-0">Signed in via:</p>
                        </li>
                        {% if social_accounts %}
                            {% for account in social_accounts %}
                                <li class="list-inline-item">
                                    <p class="text-muted small mb-4 mb-lg-0">{{ account }}</p>
                                </li>
                            {% endfor %}
                        {% else %}
                            <li class="list-inline-item">
                                <p class="text-muted small mb-4 mb-lg-0">local sign in</p>
                            </li>
                        {% endif %}
                    </ul>

                </div>
            {% endif %}
        </div>
    </div>
</footer>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
</html>

src/templates/devices.html
{% extends 'base.html' %}
{% load static %}

{% block body_block %}
    <header class="masthead text-center text-white d-flex" style="background:#cccccc !important;">
    <h1>{{ page_title }}</h1>
        <div class="container my-auto">
            <div class="row">

                {% for device in device_list %}
                <div class="col-lg-4">

                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <i class="fa fa-tasks fa-fw"></i> {{ device.device_id.type }}
                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <div class="list-group">
                                <a href="#" class="list-group-item">
                                    <span class="pull-left text-muted small"><em>Device Name: </em>
                                    </span>
                                    <i class="fa fa-tasks fa-fw"></i> {{ device.device_name }}
                                </a>

                                <a href="#" class="list-group-item">
                                    <i class="fa fa-upload fa-fw"></i> Server Rebooted
                                    <span class="pull-right text-muted small"><em>11:32 AM</em>
                                    </span>
                                </a>

                                <a href="#" class="list-group-item">
                                    <i class="fa fa-bolt fa-fw"></i> Server Crashed!
                                    <span class="pull-right text-muted small"><em>11:13 AM</em>
                                    </span>
                                </a>
                                <a href="#" class="list-group-item">
                                    <i class="fa fa-warning fa-fw"></i> Server Not Responding
                                    <span class="pull-right text-muted small"><em>10:57 AM</em>
                                    </span>
                                </a>
                            </div>
                            <!-- /.list-group -->
                            <a href="#" class="btn btn-default btn-block">View All Alerts</a>
                        </div>
                        <!-- /.panel-body -->
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </header>
{% endblock %}

src/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block body_block %}
    <header class="masthead text-center text-white d-flex" style="background:#cccccc !important;">
        <div class="container my-auto">
            <div class="row">
                <div class="col-lg-10 mx-auto">
                    <h1 class="text-uppercase">
                        <strong>{{ project_name }}</strong>
                    </h1>
                    <hr>
                </div>
                <div class="col-lg-8 mx-auto">
                    <p class="text-faded mb-5">Project By {{ developer }}</p>
                    <a class="btn btn-primary btn-xl js-scroll-trigger" href="https://github.com/ArieLevs/NalkinsCloud">Nalkins Cloud on GitHub</a>
                </div>
            </div>
        </div>
    </header>
{% endblock %}

src/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% load socialaccount %}

{% block body_block %}
    <form class="text-center border border-light p-5"
          method="POST"
          action="{% url 'nalkinscloud_ui:login_process' %}" id="login"
          name="login_form" role="form">
        {% csrf_token %}
        <!-- Email -->
        <input type="email" id="defaultLoginFormEmail" name="email" class="form-control mb-4"
               placeholder="Email" value="" required="required">

        <!-- Password -->
        <input type="password" id="defaultLoginFormPassword" name="password" class="form-control mb-4"
               placeholder="Password" value="" required="required">

        <div class="d-flex justify-content-around">
            <div>
                <!-- Remember me -->
                <div class="custom-control custom-checkbox">
                    <input type="checkbox" class="custom-control-input" id="defaultLoginFormRemember">
                    <label class="custom-control-label" for="defaultLoginFormRemember">Remember me</label>
                </div>
            </div>
            <div>
                <!-- Forgot password -->
                <a href="">Forgot password?</a>
            </div>
        </div>

        {% if error %}
            <div class="alert alert-danger" role="alert">
                {{ error }}
            </div>
        {% endif %}


        <!-- Sign in button -->
        <button class="btn btn-info btn-block my-4" type="submit">Sign in</button>
    </form>

    <div class="text-center border border-light p-5">
        <!-- Register -->
        <p>Not a member?
            <a href="">Register</a>
        </p>

        <p>or sign in with:</p>

        <div class="col text-center">
            <a class="btn btn-outline-dark" href="{% provider_login_url 'google' %}" role="button"
               style="text-transform:none">
                <img width="20px" style="margin-bottom:3px; margin-right:5px" alt="Google sign-in"
                     src="https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Google_%22G%22_Logo.svg/512px-Google_%22G%22_Logo.svg.png"/>
                Sign in with Google
            </a>
        </div>


    </div>
{% endblock %}